echo "                                                              "
echo "   /XX                                                      "
echo "  | XX                                                      "
echo " /XXXXXX    /XXXXXX  /XXXXXXX  /XXXXXXX   /XXXXXX   /XXXXXX   /XXXXXX "
echo "|_  XX_/   |____  XX| XX__  XX| XX__  XX /XX__  XX /XX__  XX /XX__  XX"
echo "  | XX      /XXXXXXX| XX  \ XX| XX  \ XX| XXXXXXXX| XX  \__/| XX  \__/"
echo "  | XX /XX /XX__  XX| XX  | XX| XX  | XX| XX_____/| XX      | XX      "
echo "  |  XXXX/ | XXXXXXX| XX  | XX| XX  | XX|  XXXXXXX| XX      | XX      "
echo "   \___/   \_______/|__/  |__/|__/  |__/ \_______/|__/      |__/      "
echo "                                                            "
echo "                                                            "
echo "                                                            "
